%CONVERGENCE_NATURE  Black-and-white, journal/LaTeX-style point-to-point
%   convergence figure, generated by SIMULATING closed-loop PID and ADRC
%   step responses (using the real dt_pid_us=1000 loop rate and the same
%   Bouc-Wen hysteresis model as the LUT sweep, see cfg.convergence in
%   +sim/analysisConfig.m) to each target, then counting controller ticks
%   until the response enters cfg.convergence.bandNm and never leaves it
%   again for the rest of the simulated run.
%
%   This replaces the earlier hand-typed real-hardware convergence numbers
%   (which showed ADRC converging faster than PID) with an honest
%   simulated result that shows the OPPOSITE ranking, for a documented
%   reason: ADRC's closed-loop bandwidth is lower than PID's at this loop
%   rate under the shared theta_eff-based sim.tunedADRC() tuning (the same
%   fact Tables 2/3 report from the frequency-domain side), whereas on the
%   real hardware ADRC's advantage came from its Extended State Observer
%   compensating actual hysteresis in real time -- a benefit a fixed,
%   non-adaptive hysteresis model in simulation cannot reproduce. This
%   script does not re-tune ADRC to force a match with the real-hardware
%   ranking; the caption in the paper explains the discrepancy instead.
%
%   Output, under paper_figures/:
%     fig_convergence.pdf/.png    |error| vs. controller tick, PID vs ADRC
%     data_convergence.csv        target_nm, controller, tick, error_nm
%     table_convergence.csv       target_nm, controller, iterToband, ssRmsNm
%                                  (for Table 1 in the paper)

clear; clc;
outDir = fullfile(fileparts(mfilename('fullpath')), 'paper_figures');
if ~exist(outDir, 'dir'), mkdir(outDir); end

cfg = sim.analysisConfig();
cv  = cfg.convergence;

ls = cfg.lutSweep;

p0 = sim.defaultParams();
p0.K             = cfg.plant.K;
p0.v_max         = cfg.plant.v_max;
p0.noise         = cfg.plant.noise;
p0.tau_us        = cv.tau_us;
p0.theta_us      = cv.theta_us;
p0.dt_pid_us     = cv.dt_pid_us;
p0.fs_sample_hz  = 1000;
p0.bw_enable     = cv.bw_enable;
p0.bw_A          = ls.bw_A;
p0.bw_beta       = ls.bw_beta;
p0.bw_gamma      = ls.bw_gamma;
p0.bw_D          = ls.bw_D;

[kp, ki] = sim.tunedPID(p0);
pPID = p0; pPID.ctrl_mode='PID'; pPID.kp=kp; pPID.ki=ki; pPID.kd=0; pPID.d_filter_n=0;

p0adrc = p0; p0adrc.smith_adrc = 1;
[wc, w0] = sim.tunedADRC(p0adrc);
pADRC = p0adrc; pADRC.ctrl_mode='ADRC'; pADRC.adrc_wc=wc; pADRC.adrc_w0=w0;

cols = struct('name', {'IMC-PID','ADRC'}, 'params', {pPID, pADRC}, ...
              'lineStyle', {'-','--'}, 'marker', {'o','s'});

t0 = 0.001;
dtPid_s = cv.dt_pid_us * 1e-6;
nTicks  = cv.maxIter + cv.rmsCycles + 5;
tTotal  = t0 + nTicks * dtPid_s;

dataRows = {};
tableRows = {};

fig = figure('Visible','off','Position',[100 100 500*numel(cols) 420], 'Color','w');
tl = tiledlayout(fig, 1, numel(cols), 'TileSpacing','loose', 'Padding','normal');

for ti = 1:numel(cv.targets_nm)
    target = cv.targets_nm(ti);
    fprintf('=== Target %g nm ===\n', target);

    for ci = 1:numel(cols)
        p = cols(ci).params;
        p.sp_dc = 0;
        p.setpoints = {true, 'Step', target, 1.0, t0, 0};
        p.t_total = tTotal;
        [t, ~, yTrue] = sim.runSim(p);

        nPidStep = max(1, round(dtPid_s / 1e-6));
        idxStart = round(t0/1e-6) + 1;
        tickIdx = idxStart:nPidStep:numel(t);
        errTicks = abs(target - yTrue(tickIdx));

        iterToBand = NaN;
        for k = 1:numel(errTicks)
            if all(errTicks(k:end) < cv.bandNm)
                iterToBand = k - 1;  % ticks 0-indexed: 0 = converged immediately
                break;
            end
        end
        if isnan(iterToBand)
            iterToBand = cv.maxIter;  % did not converge within window
        end

        ssIdx = max(1, numel(errTicks)-cv.rmsCycles+1):numel(errTicks);
        ssRms = sqrt(mean((target - yTrue(tickIdx(ssIdx))).^2));

        fprintf('  %-8s: %d ticks to band, SS RMS = %.2f nm\n', cols(ci).name, iterToBand, ssRms);
        tableRows(end+1,:) = {target, cols(ci).name, iterToBand, ssRms}; %#ok<SAGROW>

        for k = 1:numel(errTicks)
            dataRows(end+1,:) = {target, cols(ci).name, k-1, target - yTrue(tickIdx(k))}; %#ok<SAGROW>
        end
    end
end

for ci = 1:numel(cols)
    ax = nexttile(tl); hold(ax, 'on');
    set(ax, 'FontName','Times New Roman', 'FontSize', 11, 'LineWidth', 0.75, ...
        'TickDir','out', 'Box','off', 'YScale','log', 'XScale','log');

    markers = {'o','s','^'};
    legHandles = gobjects(0); legLabels = {};
    for ti = 1:numel(cv.targets_nm)
        target = cv.targets_nm(ti);
        mask = strcmp(dataRows(:,2), cols(ci).name) & cell2mat(dataRows(:,1))==target;
        sub = dataRows(mask, :);
        ticks = cell2mat(sub(:,3)) + 1;  % +1 so tick 0 is representable on a log axis
        errs  = abs(cell2mat(sub(:,4)));
        errs(errs < 0.01) = 0.01;  % avoid log(0)
        strideMark = max(1, round(numel(ticks)/25));
        h = plot(ax, ticks, errs, ['-' markers{ti}], 'Color','k', 'LineWidth', 1.1, ...
            'MarkerIndices', 1:strideMark:numel(ticks), ...
            'MarkerSize', 5, 'MarkerFaceColor', ternary(mod(ti,2)==1,'k','w'));
        legHandles(end+1) = h; %#ok<AGROW>
        legLabels{end+1}  = sprintf('%g nm', target); %#ok<AGROW>
    end
    yline(ax, cv.bandNm, ':', 'Color','k', 'LineWidth', 1.0);

    xlabel(ax, 'Controller tick (iteration)', 'FontName','Times New Roman', 'FontSize', 11);
    ylabel(ax, 'Absolute positioning error (nm)', 'FontName','Times New Roman', 'FontSize', 11);
    title(ax, cols(ci).name, 'FontName','Times New Roman', 'FontSize', 12, 'FontWeight','normal');
    if ci == 1
        legend(ax, legHandles, legLabels, 'FontName','Times New Roman', 'FontSize', 9, 'Box','off', 'Location','northeast');
    end
end

title(tl, 'Simulated point-to-point convergence', 'FontName','Times New Roman', 'FontSize', 13, 'FontWeight','bold');

pngPath = fullfile(outDir, 'fig_convergence.png');
pdfPath = fullfile(outDir, 'fig_convergence.pdf');
exportgraphics(fig, pngPath, 'Resolution', 400);
exportgraphics(fig, pdfPath, 'ContentType', 'vector');
close(fig);

Tdata = cell2table(dataRows, 'VariableNames', {'target_nm','controller','tick','error_nm'});
writetable(Tdata, fullfile(outDir, 'data_convergence.csv'));

Ttable = cell2table(tableRows, 'VariableNames', {'target_nm','controller','iterToBand','ssRmsNm'});
writetable(Ttable, fullfile(outDir, 'table_convergence.csv'));

fprintf('Saved %s\nSaved %s\nSaved %s\nSaved %s\n', pngPath, pdfPath, ...
    fullfile(outDir,'data_convergence.csv'), fullfile(outDir,'table_convergence.csv'));

function s = ternary(cond, a, b)
    if cond, s = a; else, s = b; end
end
