%LUT_SWEEP_NATURE  Black-and-white, journal/LaTeX-style voltage-displacement
%   hysteresis loop, generated by SIMULATING a bidirectional quasi-static
%   voltage sweep through the Bouc-Wen hysteresis model already built into
%   +sim/runSim.m, rather than by hand-typed real-hardware numbers in a
%   LaTeX filecontents block.
%
%   This is simulated demonstration data, not a measurement: bw_D and the
%   other Bouc-Wen parameters (cfg.lutSweep in +sim/analysisConfig.m) were
%   chosen to produce a visually clear loop at this K/voltage-range scale,
%   not fit to any real dataset. The figure and caption say so explicitly.
%
%   Method: for each voltage step, hold it constant for
%   cfg.lutSweep.settleCycles plant time constants (Euler-integrating the
%   FOPDT plant directly, since this is an open-loop sweep -- no
%   controller is involved), then record the settled displacement.
%
%   Output, under paper_figures/:
%     fig_lut_sweep.pdf/.png   ascending/descending branches
%     data_lut_sweep.csv       V, branch, displacement_nm

clear; clc;
outDir = fullfile(fileparts(mfilename('fullpath')), 'paper_figures');
if ~exist(outDir, 'dir'), mkdir(outDir); end

cfg = sim.analysisConfig();
K  = cfg.plant.K;
ls = cfg.lutSweep;

tau_us = 20;  % identified plant time constant (same value used throughout this work)
tau_s  = tau_us * 1e-6;
dt     = 1e-7;
nSettle = round(ls.settleCycles * tau_s / dt);

Vup   = 0:ls.vStep:ls.vMax;
Vdown = ls.vMax:-ls.vStep:0;
Vseq  = [Vup, Vdown(2:end)];
branch = [repmat({'up'}, 1, numel(Vup)), repmat({'down'}, 1, numel(Vdown)-1)];

z_bw = 0; prevV = 0; yState = 0;
y = zeros(size(Vseq));
for i = 1:numel(Vseq)
    du = Vseq(i) - prevV;
    z_bw = z_bw + ls.bw_A*du - ls.bw_beta*abs(du)*z_bw - ls.bw_gamma*du*abs(z_bw);
    hystComp = -ls.bw_D * z_bw;
    for k = 1:nSettle
        yState = yState + (K*Vseq(i) - yState)/tau_s*dt;
    end
    y(i) = yState + hystComp;
    prevV = Vseq(i);
end

nUp = numel(Vup);
Vup_arr   = Vseq(1:nUp);
yUp       = y(1:nUp);
Vdown_arr = Vseq(nUp:end);
yDown     = y(nUp:end);

fig = figure('Visible','off','Position',[100 100 750 620], 'Color','w');
ax = axes(fig); hold(ax, 'on');
set(ax, 'FontName','Times New Roman', 'FontSize', 11, 'LineWidth', 0.75, ...
    'TickDir','out', 'Box','off');

hUp   = plot(ax, Vup_arr,   yUp,   '-',  'Color','k', 'LineWidth', 1.3, ...
    'Marker','o', 'MarkerIndices', 1:3:numel(Vup_arr), 'MarkerSize', 5, 'MarkerFaceColor','k');
hDown = plot(ax, Vdown_arr, yDown, '--', 'Color','k', 'LineWidth', 1.3, ...
    'Marker','s', 'MarkerIndices', 1:3:numel(Vdown_arr), 'MarkerSize', 5, 'MarkerFaceColor','w');

xlabel(ax, 'Voltage (V)', 'FontName','Times New Roman', 'FontSize', 12);
ylabel(ax, 'Displacement (nm)', 'FontName','Times New Roman', 'FontSize', 12);
legend(ax, [hUp, hDown], {'ascending branch','descending branch'}, ...
    'Location','northwest', 'FontName','Times New Roman', 'FontSize', 10, 'Box','off');
title(ax, 'Simulated voltage-displacement hysteresis loop (Bouc-Wen model)', ...
    'FontName','Times New Roman', 'FontSize', 12, 'FontWeight','normal');

[maxSep, idxSep] = max(interp1(Vdown_arr, yDown, Vup_arr, 'linear', 'extrap') - yUp);
fprintf('Max branch separation: %.1f nm at V=%.2f\n', maxSep, Vup_arr(idxSep));
fprintf('Max displacement: %.1f nm at V=%.1f\n', max(y), ls.vMax);

pngPath = fullfile(outDir, 'fig_lut_sweep.png');
pdfPath = fullfile(outDir, 'fig_lut_sweep.pdf');
exportgraphics(fig, pngPath, 'Resolution', 400);
exportgraphics(fig, pdfPath, 'ContentType', 'vector');
close(fig);

Tdata = table([Vup_arr'; Vdown_arr'], [branch(1:nUp)'; branch(nUp:end)'], [yUp'; yDown'], ...
    'VariableNames', {'voltage_V','branch','displacement_nm'});
csvPath = fullfile(outDir, 'data_lut_sweep.csv');
writetable(Tdata, csvPath);

fprintf('Saved %s\nSaved %s\nSaved %s\n', pngPath, pdfPath, csvPath);
