%STEP_RESPONSE_NATURE  Black-and-white, journal/LaTeX-style FOPDT
%   step-response identification demo, generated by SIMULATING a voltage
%   step through the (hysteresis-free) plant model, adding sensor noise,
%   and then fitting K/tau/theta back out of the noisy simulated response
%   via fminsearch (no Optimization/Curve Fitting Toolbox needed) -- this
%   demonstrates that the identification procedure recovers the
%   ground-truth parameters used elsewhere in this codebase, rather than
%   claiming to identify an unknown real system. The ground-truth K/tau/
%   theta come from cfg.plant.K and cfg.convergence.tau_us/theta_us (the
%   same values used throughout the bandwidth-limit analysis), so this
%   figure and the rest of the pipeline can never silently drift apart.
%
%   Output, under paper_figures/:
%     fig_step_response.pdf/.png   simulated noisy response + fitted curve
%     data_step_response.csv       t, y_meas, y_fit

clear; clc;
outDir = fullfile(fileparts(mfilename('fullpath')), 'paper_figures');
if ~exist(outDir, 'dir'), mkdir(outDir); end

cfg = sim.analysisConfig();
sr  = cfg.stepResponse;
K_true     = cfg.plant.K;
tau_true_s = cfg.convergence.tau_us   * 1e-6;
theta_true_s = cfg.convergence.theta_us * 1e-6;

t = (0:sr.dt_s:sr.tTotal_s)';
fopdt = @(p, t) p(1) * (1 - exp(-max(t - p(3), 0) / p(2))) .* (t > p(3));

pTrue = [K_true*sr.deltaV_V, tau_true_s, theta_true_s];
yClean = fopdt(pTrue, t);

rng(1);  % reproducible simulated noise
yMeas = yClean + sr.noise_nm * randn(size(t));

cost = @(p) sum((fopdt(p, t) - yMeas).^2);
p0 = [max(yMeas), tau_true_s*2, theta_true_s*2];  % deliberately-off initial guess
opts = optimset('Display','off', 'MaxFunEvals', 20000, 'MaxIter', 20000, 'TolFun',1e-8, 'TolX',1e-10);
pFit = fminsearch(cost, p0, opts);

yFit = fopdt(pFit, t);
ssRes = sum((yMeas - yFit).^2);
ssTot = sum((yMeas - mean(yMeas)).^2);
R2 = 1 - ssRes/ssTot;

Kfit = pFit(1) / sr.deltaV_V;
fprintf('Ground truth : K=%.1f nm/V, tau=%.2f us, theta=%.2f us\n', K_true, tau_true_s*1e6, theta_true_s*1e6);
fprintf('Fitted        : K=%.1f nm/V, tau=%.2f us, theta=%.2f us, R^2=%.4f\n', Kfit, pFit(2)*1e6, pFit(3)*1e6, R2);

fig = figure('Visible','off','Position',[100 100 750 600], 'Color','w');
ax = axes(fig); hold(ax, 'on');
set(ax, 'FontName','Times New Roman', 'FontSize', 11, 'LineWidth', 0.75, ...
    'TickDir','out', 'Box','off');

strideCSV = max(1, round(numel(t)/300));
idxPlot = 1:strideCSV:numel(t);
hMeas = plot(ax, t(idxPlot)*1e6, yMeas(idxPlot), 'o', 'MarkerSize', 4, ...
    'MarkerEdgeColor','k', 'MarkerFaceColor','none', 'LineWidth', 0.75);
hFit  = plot(ax, t*1e6, yFit, '-', 'Color','k', 'LineWidth', 1.4);

xlabel(ax, 'Time (\mus)', 'FontName','Times New Roman', 'FontSize', 12);
ylabel(ax, 'Displacement (nm)', 'FontName','Times New Roman', 'FontSize', 12);
legend(ax, [hMeas, hFit], {'simulated noisy response','FOPDT fit'}, ...
    'Location','southeast', 'FontName','Times New Roman', 'FontSize', 10, 'Box','off');
title(ax, sprintf('Simulated step-response identification (R^2=%.3f)', R2), ...
    'FontName','Times New Roman', 'FontSize', 12, 'FontWeight','normal');

pngPath = fullfile(outDir, 'fig_step_response.png');
pdfPath = fullfile(outDir, 'fig_step_response.pdf');
exportgraphics(fig, pngPath, 'Resolution', 400);
exportgraphics(fig, pdfPath, 'ContentType', 'vector');
close(fig);

Tdata = table(t, yMeas, yFit, 'VariableNames', {'t_s','y_meas_nm','y_fit_nm'});
csvPath = fullfile(outDir, 'data_step_response.csv');
writetable(Tdata, csvPath);

fprintf('Saved %s\nSaved %s\nSaved %s\n', pngPath, pdfPath, csvPath);
